export const SET_EMPLOYEE_LIST_DATA = "SET_EMPLOYEE_LIST_DATA"
export const CHANGE_EMPLOYEE_LIST_PAGE = "CHANGE_EMPLOYEE_LIST_PAGE"
export const CHANGE_EMPLOYEE_LIST_ROW_PER_PAGE = "CHANGE_EMPLOYEE_LIST_ROW_PER_PAGE"
export const CHANGE_FILTER_EMPLOYEE_LIST = "CHANGE_FILTER_EMPLOYEE_LIST"