export const SET_EMPLOYEE_FORM_INITIAL_VALUES = "SET_EMPLOYEE_FORM_INITIAL_VALUES"
export const CLEAR_EMPLOYEE_FORM_INITIAL_VALUES = "CLEAR_EMPLOYEE_FORM_INITIAL_VALUES"

export const SET_EMPLOYEE_LIST_DATA = "SET_EMPLOYEE_LIST_DATA"
export const CHANGE_EMPLOYEE_LIST_PAGE = "CHANGE_EMPLOYEE_LIST_PAGE"
export const CHANGE_EMPLOYEE_LIST_ROW_PER_PAGE = "CHANGE_EMPLOYEE_LIST_ROW_PER_PAGE"
export const CHANGE_FILTER_EMPLOYEE_LIST = "CHANGE_FILTER_EMPLOYEE_LIST"